### ISSUE TITLE
Support for floating point ranges?

### ISSUE THREAD

**Issue by djc-id** [main--/rust-intervaltree#10]
Thankyou for making this library available. I am quite new to Rust so reading your code opened my eyes to some of the issues around writing generic library code. I could not see a way for me to extend your crate to support float valued ranges. 

I edited all the Ord traits to be PartialOrd and I couldn't figure out cmp::max on a PartialOrd so had to use an if statement.  It still passes your tests and mine. 

If you would be open to supporting floating point ranges that would be great for my use case.  I won't send you a pull request because my Rust code is nowhere near production quality.

**Comment by main--** [comment]
An interval tree requires its keys to be totally ordered. Floating point numbers in rust are not totally ordered, hence they do not implement `Ord`. If you still need to use them as keys for an interval tree, the correct solution is to use something like the [ordered-float](https://docs.rs/ordered-float/2.1.1/ordered_float/) crate, i.e., a wrapper that defines a total order for your floats, usually by prohibiting NaN values.

**Comment by djc-id** [comment]
Thank you for responding to me so quickly. Following your suggestion I switched to using OrderedFloats and I am able to successfully run my tests with float ranges using your library. Cheers.
