### ISSUE TITLE
Iteration order on IntervalTree

### ISSUE THREAD

**Issue by lucab** [main--/rust-intervaltree#7]
According to current docstring, `IntervalTree::iter()` iterates over the tree in "[no particular order](https://github.com/main--/rust-intervaltree/blob/ed034a3db6550496cff333e1514d70ac5302eed9/src/lib.rs#L165-L168)".

However, [by construction](https://github.com/main--/rust-intervaltree/blob/ed034a3db6550496cff333e1514d70ac5302eed9/src/lib.rs#L60), the underlying Vec is sorted by ascending order of `Range.start`.

Iterating over the set of intervals in increasing "range start" order is a common primitive used by intervals-handling algorithms, useful for example when computing the overlaps-adjusted length of the set (i.e. the [Lebesgue measure](https://cs.stackexchange.com/questions/79290/compute-lebesgue-measure-of-set-of-intervals/79295) of an `IntervalTree`).

My reading of API docs seems to suggest that, in order to iterate in ascending start order, a consumer needs to first collect the iterator and sort it. However code reading seems to suggest this is just wasted CPU and memory resources, as the iterator is in fact already sorted in that manner.

Am I missing something here? Would it be possible to state/guarantee the current "ascending range start" iteration order, so that consumers can rely on it?

**Comment by main--** [comment]
I think the idea was to allow a more efficient data structure in the future (for example the [eytzinger](https://docs.rs/eytzinger/) array layout for more efficient binary search).

You have a point though. I think this guarantee should be fine to give.

**Comment by lucab** [comment]
@main-- do you maybe prefer adding a new method which explicitly returns a sorted iterator?

Right now it would just be code duplication, but that way in the future you are still free to change the data-structure and the original iterator, while consumers can still rely on the ordered one. I'm fine either ways, happy to send a PR for whatever you prefer. And thanks for maintaining the library :)

**Comment by lucab** [comment]
@main-- thanks for the fix and the 0.2.6 release!
